### PR TITLE
Update 2 tr.json

### PR DESCRIPTION
**Pull request by TARZANHAN**
Hi!

- The articles have been corrected for Turkish users to understand them better. -> Errors in expression in Turkish were changed based on punctuation marks.
- The bot was added to a server and tested, and the translations were corrected accordingly.

(It should not be forgotten that Turkish has a sentence style independent of English)

### CODE REVIEW

**Comment by fb-sean** [comment]
Hi @TARZANHAN you got some merge conflicts could you check them? Then I can publish this version.

**Comment by TARZANHAN** [comment]
> Hi @TARZANHAN you got some merge conflicts could you check them? Then I can publish this version.

I don't know if it happened. If not, how do I do it?

**Comment by fb-sean** [comment]
> > Hi @TARZANHAN you got some merge conflicts could you check them? Then I can publish this version.
> 
> I don't know if it happened. If not, how do I do it?

Seems like with the revert its fixed

**Comment by TARZANHAN** [comment]
> > > Hi @TARZANHAN you got some merge conflicts could you check them? Then I can publish this version.
> > 
> > 
> > I don't know if it happened. If not, how do I do it?
> 
> Seems like with the revert its fixed

I deleted the conflicting commands here and I think it was solved

**Comment by TARZANHAN** [comment]
Approximately when will it be updated

**Comment by fb-sean** [comment]
@TARZANHAN it is already online 👍

**Comment by TARZANHAN** [comment]
When bot sends messages there are old messages

**Comment by fb-sean** [comment]
@TARZANHAN  now

**Comment by TARZANHAN** [comment]
now it is okay

**Pull request merged**
